
CREATE TABLE FLIGHT
(	
	AIR_CRAFT_CODE VARCHAR(30) PRIMARY KEY,	
	SOURCE_CITY VARCHAR(30),
	DESTINATION_CITY VARCHAR(30)
)

INSERT INTO FLIGHT VALUES ('EMI1', 'DUB', 'HYB')
INSERT INTO FLIGHT VALUES ('EMI2', 'DUB', 'ABD')
INSERT INTO FLIGHT VALUES ('EMI3', 'HYB', 'LSA')


create table Reservation
(
ReservationID int Identity (1001,1),	
AIR_CRAFT_CODE VARCHAR(30) REFERENCES FLIGHT(AIR_CRAFT_CODE),	
No_of_Seats int,
Class_Code varchar(10) 
)

INSERT INTO Reservation VALUES ('EMI1', 1, 'ECO')
INSERT INTO Reservation VALUES ('EMI2', 8, 'ECO')
INSERT INTO Reservation VALUES ('EMI1', 3, 'ECO')
INSERT INTO Reservation VALUES ('EMI2', 4, 'BIZ')
INSERT INTO Reservation VALUES ('EMI1', 3, 'ECO')
INSERT INTO Reservation VALUES (NULL, 3, 'ECO')
